CREATE TABLE student (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    studentCode VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE instructor (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    studentCode VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE grades (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    studentCode VARCHAR(50) UNIQUE NOT NULL
);